services:
  - type: web
    name: medusa-uploaderbot
    runtime: docker
    plan: pro
    region: virginia
    branch: main
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER
        sync: false
      - key: AUTH_USERS
        sync: false
      - key: CHANNELS
        sync: false
      - key: RENDER
        value: true
    disk:
      name: bot-storage
      mountPath: /app/downloads
      sizeGB: 20
    scaling:
      minInstances: 1
      maxInstances: 1
