# render.yaml - Render Deployment Configuration
services:
  - type: web
    plan: pro
    region: virginia
    name: medusa-Uploaderbot
    runtime: python3
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      apt-get update && apt-get install -y aria2 ffmpeg
    startCommand: python main.py
    plan: starter
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER
        sync: false
      - key: AUTH_USERS
        sync: false
      - key: CHANNELS
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: bot-storage
      mountPath: /app/downloads
      sizeGB: 20
    scaling:
      minInstances: 1
      maxInstances: 1

  - type: redis
    name: medusa-redis
    plan: starter
    region: oregon
    maxmemoryPolicy: allkeys-lru

# Optional: Database service (if you want persistent PostgreSQL instead of SQLite)
  - type: pserv
    name: medusa-database
    databaseName: medusa_bot_db
    databaseUser: medusa_user
    plan: pro
    region: virginia
